name: Use Custom Action

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run my custom action
        uses: ./.github/actions/hello-action
        with:
          name: Victor
